### ISSUE TITLE
ManyToMany::link strange behavior on not saved record

### ISSUE THREAD

**Issue by m4Dc00kie** [spiral/components#119]
Suppose I have two entities. One represents a user and the other user's role.

The user entity has the following schema definition:

``` php
protected $schema = [
    'id'       => 'primary',
    'roles'    => [
        self::MANY_TO_MANY => Role::class,
        self::INVERSE      => 'user',
    ],
];
```

And the role entity has:

``` php
protected $schema = [
    'id'          => 'primary',
    'users'       => [
        self::MANY_TO_MANY => User::class,
     ],
];
```

Then if you do something weird (or not) like this:

``` php
$user = new User();
$aRole = Role::findOne(['id' => 1]);
$user->roles()->link($aRole);
$user-save(); // => true
```

Everything will be okay but only before you check your data. The code above will do the following:
1. First it will create a record in the `role_user_map` table where the `user_id` field is `null` and the `role_id` field is `1`
2. And then it will create a record in the `user` table

It'll be much more better if the actual linking will be performed just after the `User` entity saved. But something like exception will be also good.

Sorry for my English and have a nice day :)

**Comment by wolfy-j** [comment]
nice catch.
