### ISSUE TITLE
OR statement in dbal

### ISSUE THREAD

**Issue by vvval** [spiral/components#89]
http://prntscr.com/9sfe2m causes 
Spiral\Database\Exceptions\BuilderException: Nested conditions should have defined operator. in C:\OpenServer\domains\spiral.empty\vendor\spiral\components\source\Spiral\Database\Builders\Prototypes\AbstractWhere.php at line 310

**Comment by wolfy-j** [comment]
wrong statement, nested OR has to be with @ prefix. @OR
